[features]
seeds = false
skip-lint = false
[programs.devnet]
token_mint = "4C6DmW3GPnB9vvZxvi4ikfmy2XxQs73uCNX421hBLCAb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yudiz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
